repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.9
      hooks:
          - id: ruff # Linter
            args: [--fix]
            language: system
          - id: ruff-format # Formatter
            language: system

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.15.0
      hooks:
          - id: mypy
            name: mypy
            entry: uv run mypy
            # language: python
            language: system
            types: [python]
